
print("==============================")  
print("= NAMA    : MOH. TAUFIK RAUF  ") 
print("= NIM     : 312010151         ")
print("= KELAS   : TI.20 A.1         ") 
print("==============================")

print("Please enter your full name : MOH. TAUFIK RAUF")
fullname=input()
print("Please enter nickname : TAUFIK")
nickname=input()
print("Please enter your NPM : 312010151")
npm=input()
print("Please enter place of birth : GORONTALO")
pob=input()
print("Please enter date of birth : 19")
date=input()
print("Please enter your month of birth : APRIL")
month=input()
print("Please enter year of birth : 2002")
year=input()
print("Please enter your phone number : 082189289710")
phone=input()
print("Please enter your address : SUKADAMI")
address=input()

dob=input("2020-year")

print("\n\n Assalamu'alaikum.")
print("Let me introduce my self, my name is {MOH. TAUFIK RAUF}, but you can call me {TAUFIK}, my NPM {312010151}, I was born in {GORONTALO} and iam {18} years old, I am very glad if you want to invite my house in {Perum.Citra Graha Prima}, So don't forget to call me before with the number {082189289710}, \n\n Thanks you ")